name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: make docker
      
    - name: Run Docker in background
      run: |
        set -x
        make EXTRA_DOCKER_OPTS=-d run
        sleep 20
        curl http://localhost:8080/greet
